name: Test GitHub OIDC to S3

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_DATA_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Test S3 access
        run: |
          echo "Listing latest/..."
          aws s3 ls \
            s3://indian-ev-scooter-sentiment-analysis-portfolio/latest/

          echo ""
          echo "Listing releases/..."
          aws s3 ls \
            s3://indian-ev-scooter-sentiment-analysis-portfolio/releases/

      - name: Test CP
        run: |
         echo "Testing write access"
         aws s3 cp logs/application.log s3://${{ secrets.S3_BUCKET }}/latest/application.log
         echo "Push done check from aws side"
